In [96]:
import os, config, pickle, numpy as np, pandas as pd
from nbimporter import NotebookLoader
loader = NotebookLoader()
Species, Data = loader.load_module('1_extract').Species, loader.load_module('1_extract').Data

Importing Jupyter notebook from 1_extract.ipynb
Importing Jupyter notebook from 1_extract.ipynb


# Processing the lxmx data

## Goals:
* construct projection matrix $P$ for data
* for each $P$ compute dominant & subdominant eigenvalues and their logs, $r, r_1$
* for each $P$ compute $T_c, T_g, V, r_{0a}, r_{0b}, d, G, K$ (see theory for reference)

In [97]:
SPECIES = config.load_pickle(os.path.join(config.OUTPUT_DIR, 'species.pkl'))

In [98]:
class Processing:

    def process(species):
        for data in species.data:
            matrix = data.matrix
            l_a = matrix['l(a)'].to_numpy()
            f_a = matrix['f(a)'].to_numpy()
            p_a = matrix['p(a)'].to_numpy()
            data.leslie = Processing.generate_leslie(p_a, f_a)
            
    def generate_leslie(p_a, f_a):
        N = p_a.shape[0]
        leslie = np.zeros((N, N))
        leslie[0] = f_a
        np.fill_diagonal(leslie[1:, :-1], p_a)
        return leslie

In [106]:
Processing.process(SPECIES['Red deer'])

In [111]:
vals, vecs = np.linalg.eig(SPECIES['Red deer'].data[0].leslie)

In [112]:
ix = vals.argsort()
ix = ix[::-1]

In [113]:
ix

array([ 0,  1,  2,  3,  4,  7,  8,  5,  6, 18,  9, 10, 11, 12, 13, 14, 17,
       15, 16])

In [115]:
vecs[ix]

array([[ 4.75210604e-01+0.00000000e+00j, -1.01658811e-01+5.38090938e-02j,
        -1.01658811e-01-5.38090938e-02j,  5.81048180e-02+8.80281950e-03j,
         5.81048180e-02-8.80281950e-03j,  3.68581167e-02-2.94717346e-02j,
         3.68581167e-02+2.94717346e-02j,  9.95523273e-06-2.78930023e-05j,
         9.95523273e-06+2.78930023e-05j, -8.60359382e-03+1.11646608e-03j,
        -8.60359382e-03-1.11646608e-03j, -1.01071087e-02-6.15618612e-03j,
        -1.01071087e-02+6.15618612e-03j, -1.98447498e-02-4.89623832e-03j,
        -1.98447498e-02+4.89623832e-03j, -6.81553343e-03+3.95453868e-03j,
        -6.81553343e-03-3.95453868e-03j,  1.57610841e-03+0.00000000e+00j,
        -2.86085999e-17+0.00000000e+00j],
       [ 4.02363583e-01+0.00000000e+00j, -6.42533176e-02+1.03164310e-01j,
        -6.42533176e-02-1.03164310e-01j,  4.47625493e-02-4.87344390e-02j,
         4.47625493e-02+4.87344390e-02j, -2.60543927e-02-4.74909177e-02j,
        -2.60543927e-02+4.74909177e-02j, -3.94852975e-05-4.16659720e-0

In [88]:
y = np.linalg.eig(SPECIES['Red deer'].data[0].leslie.T)

In [92]:
y.sort()
y = y[::-1]

In [93]:
y

array([ 1.06530507+0.j        ,  0.73784323+0.42928967j,
        0.73784323-0.42928967j,  0.44740612+0.66448918j,
        0.44740612-0.66448918j,  0.21053162+0.41502748j,
        0.21053162-0.41502748j,  0.13505133+0.77414174j,
        0.13505133-0.77414174j, -0.08888911+0.j        ,
       -0.14659086+0.67069449j, -0.14659086-0.67069449j,
       -0.3294725 +0.62086949j, -0.3294725 -0.62086949j,
       -0.58122858+0.44730666j, -0.58122858-0.44730666j,
       -0.60681333+0.j        , -0.65834166+0.17651063j,
       -0.65834166-0.17651063j])